version: '3.8'

services:

  initDb:
    image: orky161/acro-init:3
    environment:
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - acro-net

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 5
    volumes:
      - mysql-db:/var/lib/mysql
      - mysql-db:/var/mysql-dumps
    networks:
      - acro-net


  back:
    image: orky161/acro-back:3
    restart: always
    environment:
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - '9001:9001'
    networks:
      - acro-net

  front:
    image: orky161/acro-front:3
    restart: always
    environment:
      - SERVER_URL
    ports:
      - '9000:9000'
    networks:
      - acro-net




volumes:
  mysql-db:


networks:
  acro-net:
    driver: bridge
